[package]
name = "builder"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fatfs = { git = "https://github.com/rafalh/rust-fatfs"}
fscommon = "0.1"
anyhow = "1.0"
cargo_metadata = "*"